version: '3.7'
services:
  mysql:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user-api
      - MYSQL_USER=user-api
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - user-api-network
    ports:
      - "3306:3306"

  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www/user-api']
    networks:
      - user-api-network

  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www/user-api']
    networks:
      - user-api-network

networks:
  user-api-network:
