controllers:
    resource: ../src/Controller/
    type: attribute
    defaults:
        format: 'json'

api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
